FROM golang:1.26-alpine AS builder
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags "-s -w -extldflags '-static'" -o /bin/wallet-svc ./cmd/wallet
RUN apk add upx
RUN upx /bin/wallet-svc

FROM scratch
WORKDIR /src

COPY --from=builder /bin/wallet-svc ./wallet-svc

CMD ["./wallet-svc"]
