FROM golang:1.26-alpine AS builder
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags "-s -w -extldflags '-static'" -o /bin/callback-svc ./cmd/callback
RUN apk add --no-cache ca-certificates tzdata upx
RUN upx /bin/callback-svc

FROM scratch
WORKDIR /src

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /bin/callback-svc ./callback-svc

CMD ["./callback-svc"]
