// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Card struct {
	ID       uuid.UUID
	OwnerID  uuid.UUID
	Token    string
	Type     string
	Linkedat pgtype.Timestamp
	Last4    string
}

type Payment struct {
	ID        uuid.UUID
	CardID    uuid.UUID
	OwnerID   uuid.UUID
	Amount    pgtype.Numeric
	Currency  string
	Status    string
	CreatedAt pgtype.Timestamp
}
