// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addCard = `-- name: AddCard :one
INSERT INTO cards (owner_id, token, type, last4)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type AddCardParams struct {
	OwnerID uuid.UUID
	Token   string
	Type    string
	Last4   string
}

func (q *Queries) AddCard(ctx context.Context, arg AddCardParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, addCard,
		arg.OwnerID,
		arg.Token,
		arg.Type,
		arg.Last4,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const addPayment = `-- name: AddPayment :exec
INSERT INTO payments (owner_id, card_id, amount, currency, status)
VALUES ($1, $2, $3, $4, $5)
`

type AddPaymentParams struct {
	OwnerID  uuid.UUID
	CardID   uuid.UUID
	Amount   pgtype.Numeric
	Currency string
	Status   string
}

func (q *Queries) AddPayment(ctx context.Context, arg AddPaymentParams) error {
	_, err := q.db.Exec(ctx, addPayment,
		arg.OwnerID,
		arg.CardID,
		arg.Amount,
		arg.Currency,
		arg.Status,
	)
	return err
}

const getCardByID = `-- name: GetCardByID :one
SELECT id, owner_id, token, type, linkedAt, last4
FROM cards
WHERE id = $1
`

func (q *Queries) GetCardByID(ctx context.Context, id uuid.UUID) (Card, error) {
	row := q.db.QueryRow(ctx, getCardByID, id)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Token,
		&i.Type,
		&i.Linkedat,
		&i.Last4,
	)
	return i, err
}

const getCards = `-- name: GetCards :many
SELECT id, owner_id, token, type, linkedAt, last4
FROM cards
WHERE owner_id = $1
`

func (q *Queries) GetCards(ctx context.Context, ownerID uuid.UUID) ([]Card, error) {
	rows, err := q.db.Query(ctx, getCards, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Token,
			&i.Type,
			&i.Linkedat,
			&i.Last4,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPayments = `-- name: GetPayments :many
SELECT id, card_id, amount, currency, status, created_at
FROM payments
WHERE owner_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetPaymentsParams struct {
	OwnerID uuid.UUID
	Limit   int32
	Offset  int32
}

type GetPaymentsRow struct {
	ID        uuid.UUID
	CardID    uuid.UUID
	Amount    pgtype.Numeric
	Currency  string
	Status    string
	CreatedAt pgtype.Timestamp
}

func (q *Queries) GetPayments(ctx context.Context, arg GetPaymentsParams) ([]GetPaymentsRow, error) {
	rows, err := q.db.Query(ctx, getPayments, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPaymentsRow
	for rows.Next() {
		var i GetPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCard = `-- name: RemoveCard :exec
DELETE FROM cards
WHERE id = $1
`

func (q *Queries) RemoveCard(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeCard, id)
	return err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :exec
UPDATE payments
SET status = $2
WHERE id = $1
`

type UpdatePaymentStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error {
	_, err := q.db.Exec(ctx, updatePaymentStatus, arg.ID, arg.Status)
	return err
}
