// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddCard(ctx context.Context, arg AddCardParams) (uuid.UUID, error)
	AddPayment(ctx context.Context, arg AddPaymentParams) error
	GetCardByID(ctx context.Context, id uuid.UUID) (Card, error)
	GetCards(ctx context.Context, ownerID uuid.UUID) ([]Card, error)
	GetPayments(ctx context.Context, arg GetPaymentsParams) ([]GetPaymentsRow, error)
	RemoveCard(ctx context.Context, id uuid.UUID) error
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error
}

var _ Querier = (*Queries)(nil)
